package nl.bjornvanderlaan

import nl.bjornvanderlaan.dslexamples.example3.CurriculumVitae
import nl.bjornvanderlaan.dslexamples.example3.curriculumVitae
import nl.bjornvanderlaan.dslexamples.example3.toPrettyString
import java.time.LocalDate

fun CurriculumVitae.toPrettyString(): String {
    val sb = StringBuilder()
    sb.append("Name: $name\n")
    sb.append("Email: $email\n")
    sb.append("Phone: $phone\n")
    sb.append("\n")
    roles.forEach { section ->
        sb.append("Section: ${section.name}\n")
        section.entries.forEach { role ->
            sb.append("\tRole: ${role.title}\n")
            sb.append("\tCompany: ${role.company}\n")
            sb.append("\tStart Date: ${role.startDate}\n")
            if (role.endDate.isAfter(LocalDate.now())) {
                sb.append("\tEnd Date: ${role.endDate}\n")
            } else {
                sb.append("\tEnd Date: ${role.endDate} (current)\n")
            }
            if (role.description.isNotBlank()) {
                sb.append("\tDescription: ${role.description}\n")
            }
            sb.append("\n")
        }
        sb.append("\n")
    }
    return sb.toString()
}

fun main() {
    val myCV = curriculumVitae {
        name("Bjorn")
        email("Bvanderlaan@xebia.com")
        phoneNumber("0612345678")

        "Professional Experience" {
            "Software Engineer" {
                role at "Xebia" from "2022-02-01"

                +"Software Consultant at Xebia BV in the Netherlands"
                +"I have been working on various projects, ranging from small to large scale."
                +"Continuously learning new technologies and technologies that are not yet in use."
                +"The three comments above are (largely) generated by Github Copilot."
            }

            "Software Engineer" {
                role at "Xebia" from "2019-04-01" to "2022-01-31"

                +"I have been working on various projects, ranging from small to large scale."
                +"Continuously learning new technologies and technologies that are not yet in use."
                +"Various positions in the IT department in Netherlands and Singapore."
                +"The three comments above are (largely) generated by Github Copilot."
            }

            "Computer Science Student" {
                role at "TU Delft"
            }
        }
    }

    println(myCV.toPrettyString())
}