package nl.bjornvanderlaan

import nl.bjornvanderlaan.example1.solution1.curriculumVitae
import nl.bjornvanderlaan.example1.solution1.toPrettyString

fun main() {
    val myCV = curriculumVitae {
        name("Bjorn")
        email("Bvanderlaan@xebia.com")
        phoneNumber("0612345678")

        "Professional Experience" {
            "Software Engineer" {
                role at "Xebia" from "2022-02-01"

                +"Software Consultant at Xebia BV in the Netherlands"
                +"I have been working on various projects, ranging from small to large scale."
                +"Continuously learning new technologies and technologies that are not yet in use."
                +"The three comments above are (largely) generated by Github Copilot."
            }

            "IT Trainee" {
                role at "ING Bank NV" from "2019-04-01" to "2022-01-31"

                +"IT Trainee at ING Bank NV in the Netherlands"
                +"I have been working on various projects, ranging from small to large scale."
                +"Continuously learning new technologies and technologies that are not yet in use."
                +"Various positions in the IT department in Netherlands and Singapore."
            }

            "Computer Science Student" {
                role at "TU Delft"
            }
        }
    }

    println(myCV.toPrettyString())
}